export const LANDING = '/';
export const HOME = '/home';
export const PROFILECONFIG = '/profileconfig';
export const NEWPOST = '/newpost';
export const PROFILE = '/profile/*';
export const POST = '/post/*';
// export const CONTACT = '/contact';
export const AUTH_SIGNIN = '/auth/signin';
export const AUTH_SIGNUP = '/auth/signup';